<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Composition" Version="9.0.2" />
    <PackageReference Include="TProg.Framework.Mvvm" Version="1.0.2" />
    <PackageReference Include="TProg.Framework.Style" Version="1.0.2" />
    <PackageReference Include="TProg.Framework.Wpf" Version="1.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TProg.StarWarsDan.Data.Api\TProg.StarWarsDan.Data.Api.csproj" />
    <ProjectReference Include="..\TProg.StarWarsDan.Domain\TProg.StarWarsDan.Domain.csproj" />
  </ItemGroup>

</Project>
