<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(TProgDotNetVersion)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TProg.StarWarsDan.Domain\TProg.StarWarsDan.Domain.csproj" />
  </ItemGroup>

</Project>
