<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>$(TProgDotNetVersion)-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Composition" Version="10.0.12" />
    <PackageReference Include="TProg.Framework.Core" Version="2.0.0" />
    <PackageReference Include="TProg.Framework.Mvvm" Version="2.0.0" />
    <PackageReference Include="TProg.Framework.Style" Version="3.1.0" />
    <PackageReference Include="TProg.Framework.Wpf" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TProg.StarWarsDan.Data.Api\TProg.StarWarsDan.Data.Api.csproj" />
    <ProjectReference Include="..\TProg.StarWarsDan.Data.Swapi\TProg.StarWarsDan.Data.Swapi.csproj" />
    <ProjectReference Include="..\TProg.StarWarsDan.Ui\TProg.StarWarsDan.Ui.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>TProg.StarWarsDan.Test</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
